train_image_dir: /kuacc/users/hpc-yekin/hpc_run/description-removal/coco/training_data/train2017
train_mask_dir: /kuacc/users/hpc-yekin/hpc_run/description-removal/coco/training_data/train_metadata/masks
train_metadata_file: /kuacc/users/hpc-yekin/hpc_run/description-removal/final.json
val_image_dir: eval/images
val_mask_dir: eval/masks
embed_dim: 768
diffusion_model: botp/stable-diffusion-v1-5
diffusion_inpaint_model: benjamin-paine/stable-diffusion-v1-5-inpainting
alpha_clip_id: ViT-L/14
alpha_vision_ckpt_pth: /kuacc/users/hpc-yekin/hpc_run/ErdemAway/CLIPAway/ckpts/AlphaCLIP/clip_l14_grit+mim_fultune_6xe.pth
device: cuda
dtype: float32
train_batch_size: 8
gradient_accumulation_steps: 4
eval_interval: 200
forget_lambda: 1.0
recons_lambda: 1.0
projection_alpha: 1.0
margin_forgetting: 0.0
val_batch_size: 4
lr: 0.0001
weight_decay: 0.00001
num_epochs: 10
projection_block_ckpt_pth: /kuacc/users/hpc-yekin/hpc_run/ErdemAway/CLIPAway/ckpts/CLIPAway/model.safetensors
output_dir: surgery/
alpha_clip_embed_dim: 768
ip_adapter_embed_dim: 1024
root_dir: res
images_dir: images
number_of_hidden_layers: 6
ip_adapter_ckpt_pth: /kuacc/users/hpc-yekin/hpc_run/ErdemAway/CLIPAway/ckpts/IPAdapter/ip-adapter_sd15.bin
ip_image_encoder_ckpt_pth: /kuacc/users/hpc-yekin/hpc_run/ErdemAway/CLIPAway/ckpts/IPAdapter/image_encoder
do_zero_initialize: False
