train_image_dir: /kuacc/users/hpc-yekin/hpc_run/clipawaypp/coco/training_data/train2017
train_mask_dir: /kuacc/users/hpc-yekin/hpc_run/clipawaypp/coco/training_data/train_metadata/masks
train_metadata_file: /kuacc/users/hpc-yekin/hpc_run/clipawaypp/temp.json
val_image_dir: /kuacc/users/hpc-yekin/hpc_run/CLIPAway/assets/gradio_examples/images
val_mask_dir: /kuacc/users/hpc-yekin/hpc_run/CLIPAway/assets/gradio_examples/masks
embed_dim: 768
num_heads: 8
num_layers: 6
diffusion_model: runwayml/stable-diffusion-v1-5
alpha_clip_id: ViT-L/14
alpha_vision_ckpt_pth: /kuacc/users/hpc-yekin/hpc_run/CLIPAway/ckpts/AlphaCLIP/clip_l14_grit+mim_fultune_6xe.pth
device: cuda
dtype: float32
train_batch_size: 4
val_batch_size: 4
lr: 0.0001
weight_decay: 0.0001
num_epochs: 10
projection_block_ckpt_pth: /kuacc/users/hpc-yekin/hpc_run/CLIPAway/ckpts/CLIPAway/model.safetensors
output_dir: logs/
number_of_hidden_layers: 6
alpha_clip_embed_dim: 768
ip_adapter_embed_dim: 1024
wandb_run_name: "CLIPAWAY_CLR"
transformer_ckpt_pth: null
ip_adapter_ckpt_pth: /kuacc/users/hpc-yekin/hpc_run/CLIPAway/ckpts/IPAdapter/ip-adapter_sd15.bin
ip_image_encoder_ckpt_pth: /kuacc/users/hpc-yekin/hpc_run/CLIPAway/ckpts/IPAdapter/image_encoder