image_encoder_path: ckpts/IPAdapter/image_encoder
alpha_clip_ckpt_pth: ckpts/AlphaCLIP/clip_l14_grit+mim_fultune_6xe.pth
ip_adapter_ckpt_path: ckpts/IPAdapter/ip-adapter_sd15.bin
mlp_projection_layer_ckpt_path: ckpts/CLIPAway/model.safetensors
alpha_clip_id: ViT-L/14
sd_model_key: "runwayml/stable-diffusion-inpainting"
number_of_hidden_layers: 6
alpha_clip_embed_dim: 768
ip_adapter_embed_dim: 1024
seed: 42
scale: 1
strength: 1
